import { useRef } from "react";
import { motion, useScroll, useTransform, useSpring } from "framer-motion";
import { useIsMobile } from "@/hooks/use-mobile";
import { useNavigate } from "react-router-dom";
import {
  Zap,
  Sparkles,
  Copy,
  Hash,
  TrendingUp,
  Globe,
  Star,
  Check,
  ArrowRight,
  Play,
  Flame,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/contexts/AuthContext";

/* ── animation variants ── */
const fadeUp = {
  hidden: { opacity: 0, y: 40 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.12, duration: 0.6, ease: "easeOut" as const },
  }),
};

const scaleIn = {
  hidden: { opacity: 0, scale: 0.9 },
  visible: (i: number) => ({
    opacity: 1,
    scale: 1,
    transition: { delay: i * 0.1, duration: 0.5, ease: "easeOut" as const },
  }),
};

const staggerContainer = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.08 } },
};

const staggerItem = {
  hidden: { opacity: 0, y: 24 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" as const } },
};

/* ── parallax section wrapper ── */
function ParallaxSection({
  children,
  className,
  id,
  speed = 0.15,
}: {
  children: React.ReactNode;
  className?: string;
  id?: string;
  speed?: number;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const isMobile = useIsMobile();
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ["start end", "end start"],
  });
  const rawY = useTransform(scrollYProgress, [0, 1], [80 * speed, -80 * speed]);
  const y = useSpring(rawY, { stiffness: 100, damping: 30 });

  return (
    <section id={id} className={className}>
      <div ref={ref}>
        <motion.div style={isMobile ? undefined : { y }}>{children}</motion.div>
      </div>
    </section>
  );
}

/* ── data ── */
const features = [
  { icon: Sparkles, title: "AI-Powered Scripts", desc: "Get complete reel scripts with hooks, captions, and CTAs generated by advanced AI in seconds." },
  { icon: TrendingUp, title: "Viral Score Analysis", desc: "Each idea comes with a viral potential score so you know which content will perform best." },
  { icon: Copy, title: "One-Click Copy", desc: "Copy scripts, captions, and hashtags instantly. Paste directly into your posting app." },
  { icon: Hash, title: "Smart Hashtags", desc: "AI-curated hashtags tailored to your niche for maximum discoverability and reach." },
  { icon: Globe, title: "Multi-Language", desc: "Generate content in 25+ languages including Hindi, Spanish, Arabic, and more." },
  { icon: Star, title: "Save & Organize", desc: "Bookmark your favorite ideas and build a content library you can revisit anytime." },
];

const testimonials = [
  { name: "Priya S.", role: "Instagram Creator, 120K followers", text: "This tool literally changed my content game. I went from struggling for ideas to having a week's worth of content in 2 minutes.", avatar: "PS" },
  { name: "Marcus J.", role: "YouTube Shorts Creator", text: "The viral scores are surprisingly accurate. My top-performing shorts all came from ideas scored 90+. Absolutely love it.", avatar: "MJ" },
  { name: "Aisha K.", role: "Social Media Manager", text: "I manage 5 client accounts. This saves me hours every week. The multi-language feature is a game-changer for my international clients.", avatar: "AK" },
];

const examples = [
  {
    niche: "Beauty",
    topic: "morning skincare routine",
    viralScore: 94,
    hook: "I tried a dermatologist's 60-second morning routine for 14 days — my skin has never looked like this.",
    caption:
      "The 3 products I stopped using made the biggest difference. Save this before your next Sephora trip 💧✨",
    hashtags: "#SkincareRoutine #GlassSkin #MorningRoutine #SkincareTips #DermApproved #GRWM #BeautyHacks",
    accent: "from-pink-500/20 to-rose-500/10",
  },
  {
    niche: "Finance",
    topic: "side hustles for students",
    viralScore: 91,
    hook: "Broke college student to $4K/month in 90 days — and no, it's not dropshipping.",
    caption:
      "The 3 side hustles nobody talks about because they actually work. #2 made me $1,200 last week 💸 Comment 'HUSTLE' for the full breakdown.",
    hashtags: "#SideHustle #StudentLife #PassiveIncome #MoneyTips #FinancialFreedom #CollegeHacks #HustleCulture",
    accent: "from-emerald-500/20 to-teal-500/10",
  },
  {
    niche: "Fitness",
    topic: "10-minute home workout",
    viralScore: 88,
    hook: "Trainers won't tell you this — but 10 minutes of THIS beats an hour at the gym.",
    caption:
      "No equipment. No excuses. Just 10 minutes a day and your core will thank you in 2 weeks. Save & share with a friend 💪🔥",
    hashtags: "#HomeWorkout #FitnessMotivation #10MinuteWorkout #NoGymNoProblem #AbsWorkout #FitTok #GetFit2025",
    accent: "from-orange-500/20 to-amber-500/10",
  },
];

const pricingPlans = [
  { name: "Free", price: "₹0", period: "forever", desc: "Perfect for getting started", features: ["5 idea generations per day", "All 25 niches", "3 platforms supported", "Copy scripts & captions", "Basic hashtag suggestions"], cta: "Get Started Free", popular: false },
  { name: "Pro", price: "₹99", period: "/month", desc: "For serious content creators", features: ["Unlimited generations", "All 25 niches", "Priority AI processing", "Save unlimited ideas", "Advanced viral analytics", "Multi-language support", "Export to CSV"], cta: "Go Pro ✨", popular: true },
  { name: "Agency", price: "₹189", period: "/month", desc: "For teams & agencies", features: ["Everything in Pro", "5 team members", "Brand voice presets", "Bulk generation (50 at once)", "API access", "Priority support", "White-label exports"], cta: "Start Agency Plan", popular: false },
];

/* ── component ── */
export default function Landing() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const heroRef = useRef<HTMLDivElement>(null);

  const { scrollYProgress: heroScroll } = useScroll({
    target: heroRef,
    offset: ["start start", "end start"],
  });
  const heroY = useTransform(heroScroll, [0, 1], [0, 150]);
  const heroOpacity = useTransform(heroScroll, [0, 0.8], [1, 0]);
  const glowScale = useTransform(heroScroll, [0, 1], [1, 1.4]);
  const glowOpacity = useTransform(heroScroll, [0, 1], [1, 0]);

  const handleCTA = () => navigate(user ? "/app" : "/auth");

  return (
    <div className="relative min-h-screen bg-background overflow-x-hidden">
      {/* ── Nav ── */}
      <motion.header
        initial={{ y: -20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ duration: 0.5 }}
        className="fixed inset-x-0 top-0 z-50 border-b border-border/50 bg-background/80 backdrop-blur-lg"
      >
        <div className="container flex items-center justify-between py-4">
          <div className="flex items-center gap-2">
            <Zap className="h-6 w-6 text-primary" />
            <span className="font-display text-xl font-bold">
              <span className="gradient-text">Viral Reel</span>{" "}
              <span className="text-foreground">Generator</span>
            </span>
          </div>
          <nav className="hidden items-center gap-6 md:flex">
            <a href="#features" className="text-sm text-muted-foreground transition-colors hover:text-foreground">Features</a>
            <a href="#examples" className="text-sm text-muted-foreground transition-colors hover:text-foreground">Examples</a>
            <a href="#testimonials" className="text-sm text-muted-foreground transition-colors hover:text-foreground">Testimonials</a>
            <a href="#pricing" className="text-sm text-muted-foreground transition-colors hover:text-foreground">Pricing</a>
          </nav>
          <div className="flex items-center gap-3">
            {user ? (
              <Button variant="gradient" size="sm" onClick={() => navigate("/app")}>
                Go to App <ArrowRight className="ml-1 h-4 w-4" />
              </Button>
            ) : (
              <>
                <Button variant="ghost" size="sm" onClick={() => navigate("/auth")}>Sign In</Button>
                <Button variant="gradient" size="sm" onClick={() => navigate("/auth")}>Get Started</Button>
              </>
            )}
          </div>
        </div>
      </motion.header>

      {/* ── Hero ── */}
      <section ref={heroRef} className="relative overflow-hidden pt-32 pb-20 sm:pt-40 sm:pb-28">
        {/* Parallax glow orbs */}
        <motion.div
          style={{ scale: glowScale, opacity: glowOpacity }}
          className="pointer-events-none absolute -top-40 left-1/2 h-[500px] w-[800px] -translate-x-1/2 rounded-full bg-primary/10 blur-[120px]"
        />
        <motion.div
          style={{ scale: glowScale, opacity: glowOpacity }}
          className="pointer-events-none absolute top-20 right-0 h-[300px] w-[400px] rounded-full bg-secondary/10 blur-[100px]"
        />

        <motion.div style={{ y: heroY, opacity: heroOpacity }} className="container relative text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-4 py-1.5 text-sm font-medium text-primary"
            >
              <Sparkles className="h-4 w-4" />
              AI-Powered Content Creation
            </motion.div>

            <motion.h1
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.2, ease: [0.22, 1, 0.36, 1] }}
              className="font-display text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl lg:text-7xl"
            >
              Generate{" "}
              <span className="gradient-text">Viral Reel Ideas</span>
              <br />
              in Seconds
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.35 }}
              className="mx-auto mt-6 max-w-2xl text-lg text-muted-foreground sm:text-xl"
            >
              Stop struggling for content ideas. Our AI generates complete reel scripts,
              hooks, captions & hashtags for Instagram Reels, TikTok & YouTube Shorts.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.5 }}
              className="mt-10 flex flex-col items-center gap-4 sm:flex-row sm:justify-center"
            >
              <Button
                variant="gradient"
                size="lg"
                onClick={handleCTA}
                className="animate-pulse-glow px-8 text-base"
              >
                <Sparkles className="mr-2 h-5 w-5" />
                Start Generating — It's Free
              </Button>
              <Button variant="outline" size="lg" onClick={() => document.getElementById("features")?.scrollIntoView({ behavior: "smooth" })}>
                See How It Works
              </Button>
            </motion.div>
          </motion.div>

        </motion.div>
      </section>

      {/* ── Features ── */}
      <ParallaxSection id="features" className="border-t border-border py-20 sm:py-28" speed={0.2}>
        <div className="container">
          <div className="mb-14 text-center">
            <p className="text-sm font-medium uppercase tracking-widest text-primary">Features</p>
            <h2 className="mt-3 font-display text-3xl font-bold sm:text-4xl">
              Everything You Need to Go <span className="gradient-text">Viral</span>
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-muted-foreground">
              Powerful AI tools designed for content creators who want to grow faster on social media.
            </p>
          </div>

          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((f) => (
              <motion.div
                key={f.title}
                whileHover={{ y: -6, transition: { duration: 0.25 } }}
                className="card-gradient rounded-xl border border-border p-6 transition-colors hover:border-primary/30 hover:glow-shadow"
              >
                <motion.div
                  whileHover={{ rotate: [0, -10, 10, 0], transition: { duration: 0.5 } }}
                  className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10"
                >
                  <f.icon className="h-6 w-6 text-primary" />
                </motion.div>
                <h3 className="font-display text-lg font-semibold text-foreground">{f.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{f.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </ParallaxSection>

      {/* ── How It Works ── */}
      <ParallaxSection className="border-t border-border py-20 sm:py-28" speed={0.15}>
        <div className="container">
          <div className="mb-14 text-center">
            <p className="text-sm font-medium uppercase tracking-widest text-primary">How It Works</p>
            <h2 className="mt-3 font-display text-3xl font-bold sm:text-4xl">
              Three Steps to <span className="gradient-text">Viral Content</span>
            </h2>
          </div>

          <div className="mx-auto grid max-w-3xl gap-8 sm:grid-cols-3">
            {[
              { step: "01", title: "Pick Your Niche", desc: "Choose from 25 niches like fitness, finance, comedy, and more." },
              { step: "02", title: "Generate Ideas", desc: "AI creates 10 viral reel ideas with scripts, hooks & hashtags." },
              { step: "03", title: "Create & Post", desc: "Copy the content, create your reel, and watch it go viral." },
            ].map((s) => (
              <motion.div
                key={s.step}
                whileHover={{ scale: 1.05, transition: { duration: 0.2 } }}
                className="text-center"
              >
                <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-gradient-to-br from-primary to-accent font-display text-xl font-bold text-primary-foreground">
                  {s.step}
                </div>
                <h3 className="font-display text-lg font-semibold">{s.title}</h3>
                <p className="mt-2 text-sm text-muted-foreground">{s.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </ParallaxSection>

      {/* ── See It In Action ── */}
      <ParallaxSection id="examples" className="border-t border-border py-20 sm:py-28" speed={0.18}>
        <div className="container">
          <div className="mb-14 text-center">
            <p className="text-sm font-medium uppercase tracking-widest text-primary">See It In Action</p>
            <h2 className="mt-3 font-display text-3xl font-bold sm:text-4xl">
              Real Outputs From <span className="gradient-text">Real Topics</span>
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-muted-foreground">
              Type a topic. Get a scroll-stopping hook, a caption that converts, and a hashtag stack ready to paste. Here's exactly what you get:
            </p>
          </div>

          <motion.div
            variants={staggerContainer}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-80px" }}
            className="grid gap-6 md:grid-cols-3"
          >
            {examples.map((ex) => (
              <motion.article
                key={ex.topic}
                variants={staggerItem}
                whileHover={{ y: -6, transition: { duration: 0.25 } }}
                className="group relative flex flex-col overflow-hidden rounded-2xl border border-border card-gradient transition-colors hover:border-primary/40 hover:glow-shadow"
              >
                {/* Accent gradient top bar */}
                <div className={`h-1.5 w-full bg-gradient-to-r ${ex.accent}`} />

                <div className="flex flex-1 flex-col p-6">
                  {/* Niche + viral score */}
                  <div className="mb-4 flex items-center justify-between">
                    <span className="rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-primary">
                      {ex.niche}
                    </span>
                    <div className="flex items-center gap-1.5 text-xs font-bold text-foreground">
                      <Flame className="h-3.5 w-3.5 text-accent" />
                      <span className="gradient-text">{ex.viralScore}</span>
                      <span className="text-muted-foreground">viral</span>
                    </div>
                  </div>

                  {/* Topic input mock */}
                  <div className="mb-5">
                    <p className="mb-1.5 text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
                      Your Topic
                    </p>
                    <div className="flex items-center gap-2 rounded-lg border border-border bg-background/60 px-3 py-2.5">
                      <Sparkles className="h-3.5 w-3.5 shrink-0 text-primary" />
                      <span className="truncate text-sm font-medium text-foreground">{ex.topic}</span>
                    </div>
                  </div>

                  {/* Hook */}
                  <div className="mb-5">
                    <p className="mb-1.5 flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-widest text-primary">
                      <Play className="h-3 w-3 fill-primary" /> Hook
                    </p>
                    <p className="font-display text-base font-semibold leading-snug text-foreground">
                      "{ex.hook}"
                    </p>
                  </div>

                  {/* Caption */}
                  <div className="mb-4">
                    <p className="mb-1.5 text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
                      Caption
                    </p>
                    <p className="text-sm leading-relaxed text-foreground/80">{ex.caption}</p>
                  </div>

                  {/* Hashtags */}
                  <div className="mt-auto border-t border-border/60 pt-4">
                    <p className="mb-1.5 flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
                      <Hash className="h-3 w-3" /> Hashtags
                    </p>
                    <p className="text-xs leading-relaxed text-primary/90 break-words">{ex.hashtags}</p>
                  </div>
                </div>
              </motion.article>
            ))}
          </motion.div>

          <div className="mt-12 text-center">
            <Button variant="gradient" size="lg" onClick={handleCTA} className="px-8">
              <Sparkles className="mr-2 h-5 w-5" />
              Generate Your Own — Free
            </Button>
            <p className="mt-3 text-xs text-muted-foreground">No credit card. 5 free generations daily.</p>
          </div>
        </div>
      </ParallaxSection>

      {/* ── Testimonials ── */}
      <ParallaxSection id="testimonials" className="border-t border-border py-20 sm:py-28" speed={0.1}>
        <div className="container">
          <div className="mb-14 text-center">
            <p className="text-sm font-medium uppercase tracking-widest text-primary">Testimonials</p>
            <h2 className="mt-3 font-display text-3xl font-bold sm:text-4xl">
              Loved by <span className="gradient-text">Creators</span>
            </h2>
          </div>

          <div className="grid gap-6 sm:grid-cols-3">
            {testimonials.map((t) => (
              <motion.div
                key={t.name}
                whileHover={{ y: -4, transition: { duration: 0.2 } }}
                className="card-gradient rounded-xl border border-border p-6 transition-colors hover:border-primary/20"
              >
                <div className="mb-3 flex gap-1">
                  {[...Array(5)].map((_, j) => (
                    <Star key={j} className="h-4 w-4 fill-primary text-primary" />
                  ))}
                </div>
                <p className="text-sm leading-relaxed text-foreground/80">"{t.text}"</p>
                <div className="mt-4 flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-primary to-accent font-display text-sm font-bold text-primary-foreground">
                    {t.avatar}
                  </div>
                  <div>
                    <p className="font-display text-sm font-semibold">{t.name}</p>
                    <p className="text-xs text-muted-foreground">{t.role}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </ParallaxSection>

      {/* ── Pricing ── */}
      <ParallaxSection id="pricing" className="border-t border-border py-20 sm:py-28" speed={0.12}>
        <div className="container">
          <div className="mb-14 text-center">
            <p className="text-sm font-medium uppercase tracking-widest text-primary">Pricing</p>
            <h2 className="mt-3 font-display text-3xl font-bold sm:text-4xl">
              Simple, <span className="gradient-text">Transparent</span> Pricing
            </h2>
            <p className="mx-auto mt-4 max-w-lg text-muted-foreground">
              Start free. Upgrade when you're ready to supercharge your content.
            </p>
          </div>

          <div className="mx-auto grid max-w-4xl gap-6 sm:grid-cols-3">
            {pricingPlans.map((plan) => (
              <motion.div
                key={plan.name}
                whileHover={{ y: -8, transition: { duration: 0.25 } }}
                className={`relative rounded-xl border p-6 ${
                  plan.popular
                    ? "border-primary glow-shadow card-gradient"
                    : "border-border card-gradient"
                }`}
              >
                {plan.popular && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-gradient-to-r from-primary to-accent px-4 py-1 text-xs font-bold text-primary-foreground">
                    Most Popular
                  </div>
                )}
                <h3 className="font-display text-lg font-semibold">{plan.name}</h3>
                <div className="mt-3 flex items-baseline gap-1">
                  <span className="font-display text-4xl font-bold">{plan.price}</span>
                  <span className="text-sm text-muted-foreground">{plan.period}</span>
                </div>
                <p className="mt-2 text-sm text-muted-foreground">{plan.desc}</p>
                <ul className="mt-6 space-y-3">
                  {plan.features.map((f) => (
                    <li key={f} className="flex items-start gap-2 text-sm">
                      <Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                      <span className="text-foreground/80">{f}</span>
                    </li>
                  ))}
                </ul>
                <Button
                  variant={plan.popular ? "gradient" : "outline"}
                  className="mt-6 w-full"
                  onClick={handleCTA}
                >
                  {plan.cta}
                </Button>
              </motion.div>
            ))}
          </div>
        </div>
      </ParallaxSection>

      {/* ── Final CTA ── */}
      <section className="relative border-t border-border py-20 sm:py-28 overflow-hidden">
        <motion.div
          animate={{ scale: [1, 1.2, 1], opacity: [0.3, 0.5, 0.3] }}
          transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
          className="pointer-events-none absolute left-1/2 top-1/2 h-[400px] w-[600px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary/8 blur-[100px]"
        />
        <div className="container relative text-center">
          <h2 className="font-display text-3xl font-bold sm:text-4xl">
            Ready to Go <span className="gradient-text">Viral</span>?
          </h2>
          <p className="mx-auto mt-4 max-w-lg text-muted-foreground">
            Join thousands of creators using AI to generate scroll-stopping content every day.
          </p>
          <div className="mt-8">
            <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.97 }}>
              <Button variant="gradient" size="lg" onClick={handleCTA} className="animate-pulse-glow px-8 text-base">
                <Sparkles className="mr-2 h-5 w-5" />
                Start Generating — It's Free
              </Button>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className="border-t border-border py-10">
        <div className="container flex flex-col items-center justify-between gap-4 sm:flex-row">
          <div className="flex items-center gap-2">
            <Zap className="h-5 w-5 text-primary" />
            <span className="font-display text-sm font-bold">
              <span className="gradient-text">Viral Reel</span> Generator
            </span>
          </div>
          <p className="text-sm text-muted-foreground">
            © {new Date().getFullYear()} Viral Reel Generator. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
