import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import {
  Zap,
  Sparkles,
  Copy,
  Hash,
  TrendingUp,
  Globe,
  Star,
  Check,
  ArrowRight,
  Instagram,
  Youtube,
  Facebook,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/contexts/AuthContext";

const fadeUp = {
  hidden: { opacity: 0, y: 30 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.1, duration: 0.5 },
  }),
};

const features = [
  {
    icon: Sparkles,
    title: "AI-Powered Scripts",
    desc: "Get complete reel scripts with hooks, captions, and CTAs generated by advanced AI in seconds.",
  },
  {
    icon: TrendingUp,
    title: "Viral Score Analysis",
    desc: "Each idea comes with a viral potential score so you know which content will perform best.",
  },
  {
    icon: Copy,
    title: "One-Click Copy",
    desc: "Copy scripts, captions, and hashtags instantly. Paste directly into your posting app.",
  },
  {
    icon: Hash,
    title: "Smart Hashtags",
    desc: "AI-curated hashtags tailored to your niche for maximum discoverability and reach.",
  },
  {
    icon: Globe,
    title: "Multi-Language",
    desc: "Generate content in 25+ languages including Hindi, Spanish, Arabic, and more.",
  },
  {
    icon: Star,
    title: "Save & Organize",
    desc: "Bookmark your favorite ideas and build a content library you can revisit anytime.",
  },
];

const testimonials = [
  {
    name: "Priya S.",
    role: "Instagram Creator, 120K followers",
    text: "This tool literally changed my content game. I went from struggling for ideas to having a week's worth of content in 2 minutes.",
    avatar: "PS",
  },
  {
    name: "Marcus J.",
    role: "YouTube Shorts Creator",
    text: "The viral scores are surprisingly accurate. My top-performing shorts all came from ideas scored 90+. Absolutely love it.",
    avatar: "MJ",
  },
  {
    name: "Aisha K.",
    role: "Social Media Manager",
    text: "I manage 5 client accounts. This saves me hours every week. The multi-language feature is a game-changer for my international clients.",
    avatar: "AK",
  },
];

const pricingPlans = [
  {
    name: "Free",
    price: "$0",
    period: "forever",
    desc: "Perfect for getting started",
    features: [
      "5 idea generations per day",
      "All 25 niches",
      "3 platforms supported",
      "Copy scripts & captions",
      "Basic hashtag suggestions",
    ],
    cta: "Get Started Free",
    popular: false,
  },
  {
    name: "Pro",
    price: "$9",
    period: "/month",
    desc: "For serious content creators",
    features: [
      "Unlimited generations",
      "All 25 niches",
      "Priority AI processing",
      "Save unlimited ideas",
      "Advanced viral analytics",
      "Multi-language support",
      "Export to CSV",
    ],
    cta: "Go Pro ✨",
    popular: true,
  },
  {
    name: "Agency",
    price: "$29",
    period: "/month",
    desc: "For teams & agencies",
    features: [
      "Everything in Pro",
      "5 team members",
      "Brand voice presets",
      "Bulk generation (50 at once)",
      "API access",
      "Priority support",
      "White-label exports",
    ],
    cta: "Start Agency Plan",
    popular: false,
  },
];

export default function Landing() {
  const navigate = useNavigate();
  const { user } = useAuth();

  const handleCTA = () => {
    navigate(user ? "/app" : "/auth");
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Nav */}
      <header className="fixed inset-x-0 top-0 z-50 border-b border-border/50 bg-background/80 backdrop-blur-lg">
        <div className="container flex items-center justify-between py-4">
          <div className="flex items-center gap-2">
            <Zap className="h-6 w-6 text-primary" />
            <span className="font-display text-xl font-bold">
              <span className="gradient-text">Viral Reel</span>{" "}
              <span className="text-foreground">Generator</span>
            </span>
          </div>
          <nav className="hidden items-center gap-6 md:flex">
            <a href="#features" className="text-sm text-muted-foreground transition-colors hover:text-foreground">Features</a>
            <a href="#testimonials" className="text-sm text-muted-foreground transition-colors hover:text-foreground">Testimonials</a>
            <a href="#pricing" className="text-sm text-muted-foreground transition-colors hover:text-foreground">Pricing</a>
          </nav>
          <div className="flex items-center gap-3">
            {user ? (
              <Button variant="gradient" size="sm" onClick={() => navigate("/app")}>
                Go to App <ArrowRight className="ml-1 h-4 w-4" />
              </Button>
            ) : (
              <>
                <Button variant="ghost" size="sm" onClick={() => navigate("/auth")}>Sign In</Button>
                <Button variant="gradient" size="sm" onClick={() => navigate("/auth")}>Get Started</Button>
              </>
            )}
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="relative overflow-hidden pt-32 pb-20 sm:pt-40 sm:pb-28">
        {/* Glow effects */}
        <div className="pointer-events-none absolute -top-40 left-1/2 h-[500px] w-[800px] -translate-x-1/2 rounded-full bg-primary/10 blur-[120px]" />
        <div className="pointer-events-none absolute top-20 right-0 h-[300px] w-[400px] rounded-full bg-secondary/10 blur-[100px]" />

        <div className="container relative text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-4 py-1.5 text-sm font-medium text-primary">
              <Sparkles className="h-4 w-4" />
              AI-Powered Content Creation
            </div>

            <h1 className="font-display text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl lg:text-7xl">
              Generate{" "}
              <span className="gradient-text">Viral Reel Ideas</span>
              <br />
              in Seconds
            </h1>

            <p className="mx-auto mt-6 max-w-2xl text-lg text-muted-foreground sm:text-xl">
              Stop struggling for content ideas. Our AI generates complete reel scripts,
              hooks, captions & hashtags for Instagram, YouTube Shorts & Facebook Reels.
            </p>

            <div className="mt-10 flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
              <Button
                variant="gradient"
                size="lg"
                onClick={handleCTA}
                className="animate-pulse-glow px-8 text-base"
              >
                <Sparkles className="mr-2 h-5 w-5" />
                Start Generating — It's Free
              </Button>
              <Button variant="outline" size="lg" onClick={() => document.getElementById("features")?.scrollIntoView({ behavior: "smooth" })}>
                See How It Works
              </Button>
            </div>
          </motion.div>

          {/* Platform badges */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.5 }}
            className="mt-12 flex items-center justify-center gap-6 text-muted-foreground"
          >
            <span className="text-sm">Works with</span>
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-1.5 rounded-full bg-muted px-3 py-1.5 text-sm">
                <Instagram className="h-4 w-4 text-pink-400" /> Instagram
              </div>
              <div className="flex items-center gap-1.5 rounded-full bg-muted px-3 py-1.5 text-sm">
                <Youtube className="h-4 w-4 text-red-400" /> YouTube
              </div>
              <div className="flex items-center gap-1.5 rounded-full bg-muted px-3 py-1.5 text-sm">
                <Facebook className="h-4 w-4 text-blue-400" /> Facebook
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="border-t border-border py-20 sm:py-28">
        <div className="container">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            className="mb-14 text-center"
          >
            <motion.p variants={fadeUp} custom={0} className="text-sm font-medium uppercase tracking-widest text-primary">
              Features
            </motion.p>
            <motion.h2 variants={fadeUp} custom={1} className="mt-3 font-display text-3xl font-bold sm:text-4xl">
              Everything You Need to Go <span className="gradient-text">Viral</span>
            </motion.h2>
            <motion.p variants={fadeUp} custom={2} className="mx-auto mt-4 max-w-xl text-muted-foreground">
              Powerful AI tools designed for content creators who want to grow faster on social media.
            </motion.p>
          </motion.div>

          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((f, i) => (
              <motion.div
                key={f.title}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: "-50px" }}
                variants={fadeUp}
                custom={i}
                className="card-gradient rounded-xl border border-border p-6 transition-all hover:border-primary/30 hover:glow-shadow"
              >
                <div className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10">
                  <f.icon className="h-6 w-6 text-primary" />
                </div>
                <h3 className="font-display text-lg font-semibold text-foreground">{f.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{f.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="border-t border-border py-20 sm:py-28">
        <div className="container">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            className="mb-14 text-center"
          >
            <motion.p variants={fadeUp} custom={0} className="text-sm font-medium uppercase tracking-widest text-primary">
              How It Works
            </motion.p>
            <motion.h2 variants={fadeUp} custom={1} className="mt-3 font-display text-3xl font-bold sm:text-4xl">
              Three Steps to <span className="gradient-text">Viral Content</span>
            </motion.h2>
          </motion.div>

          <div className="mx-auto grid max-w-3xl gap-8 sm:grid-cols-3">
            {[
              { step: "01", title: "Pick Your Niche", desc: "Choose from 25 niches like fitness, finance, comedy, and more." },
              { step: "02", title: "Generate Ideas", desc: "AI creates 10 viral reel ideas with scripts, hooks & hashtags." },
              { step: "03", title: "Create & Post", desc: "Copy the content, create your reel, and watch it go viral." },
            ].map((s, i) => (
              <motion.div
                key={s.step}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                variants={fadeUp}
                custom={i}
                className="text-center"
              >
                <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-gradient-to-br from-primary to-accent font-display text-xl font-bold text-primary-foreground">
                  {s.step}
                </div>
                <h3 className="font-display text-lg font-semibold">{s.title}</h3>
                <p className="mt-2 text-sm text-muted-foreground">{s.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section id="testimonials" className="border-t border-border py-20 sm:py-28">
        <div className="container">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            className="mb-14 text-center"
          >
            <motion.p variants={fadeUp} custom={0} className="text-sm font-medium uppercase tracking-widest text-primary">
              Testimonials
            </motion.p>
            <motion.h2 variants={fadeUp} custom={1} className="mt-3 font-display text-3xl font-bold sm:text-4xl">
              Loved by <span className="gradient-text">Creators</span>
            </motion.h2>
          </motion.div>

          <div className="grid gap-6 sm:grid-cols-3">
            {testimonials.map((t, i) => (
              <motion.div
                key={t.name}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                variants={fadeUp}
                custom={i}
                className="card-gradient rounded-xl border border-border p-6"
              >
                <div className="mb-3 flex gap-1">
                  {[...Array(5)].map((_, j) => (
                    <Star key={j} className="h-4 w-4 fill-primary text-primary" />
                  ))}
                </div>
                <p className="text-sm leading-relaxed text-foreground/80">"{t.text}"</p>
                <div className="mt-4 flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-primary to-accent font-display text-sm font-bold text-primary-foreground">
                    {t.avatar}
                  </div>
                  <div>
                    <p className="font-display text-sm font-semibold">{t.name}</p>
                    <p className="text-xs text-muted-foreground">{t.role}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="border-t border-border py-20 sm:py-28">
        <div className="container">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            className="mb-14 text-center"
          >
            <motion.p variants={fadeUp} custom={0} className="text-sm font-medium uppercase tracking-widest text-primary">
              Pricing
            </motion.p>
            <motion.h2 variants={fadeUp} custom={1} className="mt-3 font-display text-3xl font-bold sm:text-4xl">
              Simple, <span className="gradient-text">Transparent</span> Pricing
            </motion.h2>
            <motion.p variants={fadeUp} custom={2} className="mx-auto mt-4 max-w-lg text-muted-foreground">
              Start free. Upgrade when you're ready to supercharge your content.
            </motion.p>
          </motion.div>

          <div className="mx-auto grid max-w-4xl gap-6 sm:grid-cols-3">
            {pricingPlans.map((plan, i) => (
              <motion.div
                key={plan.name}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                variants={fadeUp}
                custom={i}
                className={`relative rounded-xl border p-6 ${
                  plan.popular
                    ? "border-primary glow-shadow card-gradient"
                    : "border-border card-gradient"
                }`}
              >
                {plan.popular && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-gradient-to-r from-primary to-accent px-4 py-1 text-xs font-bold text-primary-foreground">
                    Most Popular
                  </div>
                )}
                <h3 className="font-display text-lg font-semibold">{plan.name}</h3>
                <div className="mt-3 flex items-baseline gap-1">
                  <span className="font-display text-4xl font-bold">{plan.price}</span>
                  <span className="text-sm text-muted-foreground">{plan.period}</span>
                </div>
                <p className="mt-2 text-sm text-muted-foreground">{plan.desc}</p>
                <ul className="mt-6 space-y-3">
                  {plan.features.map((f) => (
                    <li key={f} className="flex items-start gap-2 text-sm">
                      <Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                      <span className="text-foreground/80">{f}</span>
                    </li>
                  ))}
                </ul>
                <Button
                  variant={plan.popular ? "gradient" : "outline"}
                  className="mt-6 w-full"
                  onClick={handleCTA}
                >
                  {plan.cta}
                </Button>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="border-t border-border py-20 sm:py-28">
        <div className="container text-center">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
          >
            <motion.h2 variants={fadeUp} custom={0} className="font-display text-3xl font-bold sm:text-4xl">
              Ready to Go <span className="gradient-text">Viral</span>?
            </motion.h2>
            <motion.p variants={fadeUp} custom={1} className="mx-auto mt-4 max-w-lg text-muted-foreground">
              Join thousands of creators using AI to generate scroll-stopping content every day.
            </motion.p>
            <motion.div variants={fadeUp} custom={2} className="mt-8">
              <Button variant="gradient" size="lg" onClick={handleCTA} className="animate-pulse-glow px-8 text-base">
                <Sparkles className="mr-2 h-5 w-5" />
                Start Generating — It's Free
              </Button>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border py-10">
        <div className="container flex flex-col items-center justify-between gap-4 sm:flex-row">
          <div className="flex items-center gap-2">
            <Zap className="h-5 w-5 text-primary" />
            <span className="font-display text-sm font-bold">
              <span className="gradient-text">Viral Reel</span> Generator
            </span>
          </div>
          <p className="text-sm text-muted-foreground">
            © {new Date().getFullYear()} Viral Reel Generator. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
