import { useRef } from "react";
import { motion, useScroll, useTransform, useSpring } from "framer-motion";
import { useNavigate } from "react-router-dom";
import {
  Zap,
  Sparkles,
  Copy,
  Hash,
  TrendingUp,
  Globe,
  Star,
  Check,
  ArrowRight,
  Instagram,
  Youtube,
  Facebook,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/contexts/AuthContext";

/* ── animation variants ── */
const fadeUp = {
  hidden: { opacity: 0, y: 40 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.12, duration: 0.6, ease: "easeOut" as const },
  }),
};

const scaleIn = {
  hidden: { opacity: 0, scale: 0.9 },
  visible: (i: number) => ({
    opacity: 1,
    scale: 1,
    transition: { delay: i * 0.1, duration: 0.5, ease: "easeOut" as const },
  }),
};

const staggerContainer = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.08 } },
};

const staggerItem = {
  hidden: { opacity: 0, y: 24 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" as const } },
};

/* ── parallax section wrapper ── */
function ParallaxSection({
  children,
  className,
  id,
  speed = 0.15,
}: {
  children: React.ReactNode;
  className?: string;
  id?: string;
  speed?: number;
}) {
  const ref = useRef<HTMLElement>(null);
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ["start end", "end start"],
  });
  const y = useTransform(scrollYProgress, [0, 1], [80 * speed, -80 * speed]);
  const smoothY = useSpring(y, { stiffness: 100, damping: 30 });

  return (
    <section ref={ref} id={id} className={className}>
      <motion.div style={{ y: smoothY }}>{children}</motion.div>
    </section>
  );
}

/* ── data ── */
const features = [
  { icon: Sparkles, title: "AI-Powered Scripts", desc: "Get complete reel scripts with hooks, captions, and CTAs generated by advanced AI in seconds." },
  { icon: TrendingUp, title: "Viral Score Analysis", desc: "Each idea comes with a viral potential score so you know which content will perform best." },
  { icon: Copy, title: "One-Click Copy", desc: "Copy scripts, captions, and hashtags instantly. Paste directly into your posting app." },
  { icon: Hash, title: "Smart Hashtags", desc: "AI-curated hashtags tailored to your niche for maximum discoverability and reach." },
  { icon: Globe, title: "Multi-Language", desc: "Generate content in 25+ languages including Hindi, Spanish, Arabic, and more." },
  { icon: Star, title: "Save & Organize", desc: "Bookmark your favorite ideas and build a content library you can revisit anytime." },
];

const testimonials = [
  { name: "Priya S.", role: "Instagram Creator, 120K followers", text: "This tool literally changed my content game. I went from struggling for ideas to having a week's worth of content in 2 minutes.", avatar: "PS" },
  { name: "Marcus J.", role: "YouTube Shorts Creator", text: "The viral scores are surprisingly accurate. My top-performing shorts all came from ideas scored 90+. Absolutely love it.", avatar: "MJ" },
  { name: "Aisha K.", role: "Social Media Manager", text: "I manage 5 client accounts. This saves me hours every week. The multi-language feature is a game-changer for my international clients.", avatar: "AK" },
];

const pricingPlans = [
  { name: "Free", price: "$0", period: "forever", desc: "Perfect for getting started", features: ["5 idea generations per day", "All 25 niches", "3 platforms supported", "Copy scripts & captions", "Basic hashtag suggestions"], cta: "Get Started Free", popular: false },
  { name: "Pro", price: "$9", period: "/month", desc: "For serious content creators", features: ["Unlimited generations", "All 25 niches", "Priority AI processing", "Save unlimited ideas", "Advanced viral analytics", "Multi-language support", "Export to CSV"], cta: "Go Pro ✨", popular: true },
  { name: "Agency", price: "$29", period: "/month", desc: "For teams & agencies", features: ["Everything in Pro", "5 team members", "Brand voice presets", "Bulk generation (50 at once)", "API access", "Priority support", "White-label exports"], cta: "Start Agency Plan", popular: false },
];

/* ── component ── */
export default function Landing() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const heroRef = useRef<HTMLDivElement>(null);

  const { scrollYProgress: heroScroll } = useScroll({
    target: heroRef,
    offset: ["start start", "end start"],
  });
  const heroY = useTransform(heroScroll, [0, 1], [0, 150]);
  const heroOpacity = useTransform(heroScroll, [0, 0.8], [1, 0]);
  const glowScale = useTransform(heroScroll, [0, 1], [1, 1.4]);
  const glowOpacity = useTransform(heroScroll, [0, 1], [1, 0]);

  const handleCTA = () => navigate(user ? "/app" : "/auth");

  return (
    <div className="min-h-screen bg-background overflow-x-hidden">
      {/* ── Nav ── */}
      <motion.header
        initial={{ y: -20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ duration: 0.5 }}
        className="fixed inset-x-0 top-0 z-50 border-b border-border/50 bg-background/80 backdrop-blur-lg"
      >
        <div className="container flex items-center justify-between py-4">
          <div className="flex items-center gap-2">
            <Zap className="h-6 w-6 text-primary" />
            <span className="font-display text-xl font-bold">
              <span className="gradient-text">Viral Reel</span>{" "}
              <span className="text-foreground">Generator</span>
            </span>
          </div>
          <nav className="hidden items-center gap-6 md:flex">
            <a href="#features" className="text-sm text-muted-foreground transition-colors hover:text-foreground">Features</a>
            <a href="#testimonials" className="text-sm text-muted-foreground transition-colors hover:text-foreground">Testimonials</a>
            <a href="#pricing" className="text-sm text-muted-foreground transition-colors hover:text-foreground">Pricing</a>
          </nav>
          <div className="flex items-center gap-3">
            {user ? (
              <Button variant="gradient" size="sm" onClick={() => navigate("/app")}>
                Go to App <ArrowRight className="ml-1 h-4 w-4" />
              </Button>
            ) : (
              <>
                <Button variant="ghost" size="sm" onClick={() => navigate("/auth")}>Sign In</Button>
                <Button variant="gradient" size="sm" onClick={() => navigate("/auth")}>Get Started</Button>
              </>
            )}
          </div>
        </div>
      </motion.header>

      {/* ── Hero ── */}
      <section ref={heroRef} className="relative overflow-hidden pt-32 pb-20 sm:pt-40 sm:pb-28">
        {/* Parallax glow orbs */}
        <motion.div
          style={{ scale: glowScale, opacity: glowOpacity }}
          className="pointer-events-none absolute -top-40 left-1/2 h-[500px] w-[800px] -translate-x-1/2 rounded-full bg-primary/10 blur-[120px]"
        />
        <motion.div
          style={{ scale: glowScale, opacity: glowOpacity }}
          className="pointer-events-none absolute top-20 right-0 h-[300px] w-[400px] rounded-full bg-secondary/10 blur-[100px]"
        />

        <motion.div style={{ y: heroY, opacity: heroOpacity }} className="container relative text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-4 py-1.5 text-sm font-medium text-primary"
            >
              <Sparkles className="h-4 w-4" />
              AI-Powered Content Creation
            </motion.div>

            <motion.h1
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.2, ease: [0.22, 1, 0.36, 1] }}
              className="font-display text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl lg:text-7xl"
            >
              Generate{" "}
              <span className="gradient-text">Viral Reel Ideas</span>
              <br />
              in Seconds
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.35 }}
              className="mx-auto mt-6 max-w-2xl text-lg text-muted-foreground sm:text-xl"
            >
              Stop struggling for content ideas. Our AI generates complete reel scripts,
              hooks, captions & hashtags for Instagram, YouTube Shorts & Facebook Reels.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.5 }}
              className="mt-10 flex flex-col items-center gap-4 sm:flex-row sm:justify-center"
            >
              <Button
                variant="gradient"
                size="lg"
                onClick={handleCTA}
                className="animate-pulse-glow px-8 text-base"
              >
                <Sparkles className="mr-2 h-5 w-5" />
                Start Generating — It's Free
              </Button>
              <Button variant="outline" size="lg" onClick={() => document.getElementById("features")?.scrollIntoView({ behavior: "smooth" })}>
                See How It Works
              </Button>
            </motion.div>
          </motion.div>

          {/* Platform badges */}
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.7, duration: 0.5 }}
            className="mt-12 flex items-center justify-center gap-6 text-muted-foreground"
          >
            <span className="text-sm">Works with</span>
            <motion.div
              variants={staggerContainer}
              initial="hidden"
              animate="visible"
              className="flex items-center gap-4"
            >
              {[
                { icon: Instagram, label: "Instagram", color: "text-accent" },
                { icon: Youtube, label: "YouTube", color: "text-destructive" },
                { icon: Facebook, label: "Facebook", color: "text-primary" },
              ].map((p) => (
                <motion.div
                  key={p.label}
                  variants={staggerItem}
                  whileHover={{ scale: 1.05, y: -2 }}
                  className="flex items-center gap-1.5 rounded-full bg-muted px-3 py-1.5 text-sm transition-colors hover:bg-muted/80"
                >
                  <p.icon className={`h-4 w-4 ${p.color}`} /> {p.label}
                </motion.div>
              ))}
            </motion.div>
          </motion.div>
        </motion.div>
      </section>

      {/* ── Features ── */}
      <ParallaxSection id="features" className="border-t border-border py-20 sm:py-28" speed={0.2}>
        <div className="container">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            className="mb-14 text-center"
          >
            <motion.p variants={fadeUp} custom={0} className="text-sm font-medium uppercase tracking-widest text-primary">
              Features
            </motion.p>
            <motion.h2 variants={fadeUp} custom={1} className="mt-3 font-display text-3xl font-bold sm:text-4xl">
              Everything You Need to Go <span className="gradient-text">Viral</span>
            </motion.h2>
            <motion.p variants={fadeUp} custom={2} className="mx-auto mt-4 max-w-xl text-muted-foreground">
              Powerful AI tools designed for content creators who want to grow faster on social media.
            </motion.p>
          </motion.div>

          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((f, i) => (
              <motion.div
                key={f.title}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: "-50px" }}
                variants={scaleIn}
                custom={i}
                whileHover={{ y: -6, transition: { duration: 0.25 } }}
                className="card-gradient rounded-xl border border-border p-6 transition-colors hover:border-primary/30 hover:glow-shadow"
              >
                <motion.div
                  whileHover={{ rotate: [0, -10, 10, 0], transition: { duration: 0.5 } }}
                  className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10"
                >
                  <f.icon className="h-6 w-6 text-primary" />
                </motion.div>
                <h3 className="font-display text-lg font-semibold text-foreground">{f.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{f.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </ParallaxSection>

      {/* ── How It Works ── */}
      <ParallaxSection className="border-t border-border py-20 sm:py-28" speed={0.15}>
        <div className="container">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            className="mb-14 text-center"
          >
            <motion.p variants={fadeUp} custom={0} className="text-sm font-medium uppercase tracking-widest text-primary">
              How It Works
            </motion.p>
            <motion.h2 variants={fadeUp} custom={1} className="mt-3 font-display text-3xl font-bold sm:text-4xl">
              Three Steps to <span className="gradient-text">Viral Content</span>
            </motion.h2>
          </motion.div>

          <div className="mx-auto grid max-w-3xl gap-8 sm:grid-cols-3">
            {[
              { step: "01", title: "Pick Your Niche", desc: "Choose from 25 niches like fitness, finance, comedy, and more." },
              { step: "02", title: "Generate Ideas", desc: "AI creates 10 viral reel ideas with scripts, hooks & hashtags." },
              { step: "03", title: "Create & Post", desc: "Copy the content, create your reel, and watch it go viral." },
            ].map((s, i) => (
              <motion.div
                key={s.step}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                variants={fadeUp}
                custom={i}
                whileHover={{ scale: 1.05, transition: { duration: 0.2 } }}
                className="text-center"
              >
                <motion.div
                  initial={{ scale: 0, rotate: -180 }}
                  whileInView={{ scale: 1, rotate: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.15 + 0.2, duration: 0.5, type: "spring", stiffness: 200 }}
                  className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-gradient-to-br from-primary to-accent font-display text-xl font-bold text-primary-foreground"
                >
                  {s.step}
                </motion.div>
                <h3 className="font-display text-lg font-semibold">{s.title}</h3>
                <p className="mt-2 text-sm text-muted-foreground">{s.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </ParallaxSection>

      {/* ── Testimonials ── */}
      <ParallaxSection id="testimonials" className="border-t border-border py-20 sm:py-28" speed={0.1}>
        <div className="container">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            className="mb-14 text-center"
          >
            <motion.p variants={fadeUp} custom={0} className="text-sm font-medium uppercase tracking-widest text-primary">
              Testimonials
            </motion.p>
            <motion.h2 variants={fadeUp} custom={1} className="mt-3 font-display text-3xl font-bold sm:text-4xl">
              Loved by <span className="gradient-text">Creators</span>
            </motion.h2>
          </motion.div>

          <div className="grid gap-6 sm:grid-cols-3">
            {testimonials.map((t, i) => (
              <motion.div
                key={t.name}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                variants={fadeUp}
                custom={i}
                whileHover={{ y: -4, transition: { duration: 0.2 } }}
                className="card-gradient rounded-xl border border-border p-6 transition-colors hover:border-primary/20"
              >
                <motion.div
                  initial={{ opacity: 0 }}
                  whileInView={{ opacity: 1 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1 + 0.3 }}
                  className="mb-3 flex gap-1"
                >
                  {[...Array(5)].map((_, j) => (
                    <motion.div
                      key={j}
                      initial={{ opacity: 0, scale: 0 }}
                      whileInView={{ opacity: 1, scale: 1 }}
                      viewport={{ once: true }}
                      transition={{ delay: i * 0.1 + j * 0.05 + 0.3, type: "spring", stiffness: 300 }}
                    >
                      <Star className="h-4 w-4 fill-primary text-primary" />
                    </motion.div>
                  ))}
                </motion.div>
                <p className="text-sm leading-relaxed text-foreground/80">"{t.text}"</p>
                <div className="mt-4 flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-primary to-accent font-display text-sm font-bold text-primary-foreground">
                    {t.avatar}
                  </div>
                  <div>
                    <p className="font-display text-sm font-semibold">{t.name}</p>
                    <p className="text-xs text-muted-foreground">{t.role}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </ParallaxSection>

      {/* ── Pricing ── */}
      <ParallaxSection id="pricing" className="border-t border-border py-20 sm:py-28" speed={0.12}>
        <div className="container">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            className="mb-14 text-center"
          >
            <motion.p variants={fadeUp} custom={0} className="text-sm font-medium uppercase tracking-widest text-primary">
              Pricing
            </motion.p>
            <motion.h2 variants={fadeUp} custom={1} className="mt-3 font-display text-3xl font-bold sm:text-4xl">
              Simple, <span className="gradient-text">Transparent</span> Pricing
            </motion.h2>
            <motion.p variants={fadeUp} custom={2} className="mx-auto mt-4 max-w-lg text-muted-foreground">
              Start free. Upgrade when you're ready to supercharge your content.
            </motion.p>
          </motion.div>

          <div className="mx-auto grid max-w-4xl gap-6 sm:grid-cols-3">
            {pricingPlans.map((plan, i) => (
              <motion.div
                key={plan.name}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                variants={scaleIn}
                custom={i}
                whileHover={{
                  y: -8,
                  transition: { duration: 0.25 },
                }}
                className={`relative rounded-xl border p-6 ${
                  plan.popular
                    ? "border-primary glow-shadow card-gradient"
                    : "border-border card-gradient"
                }`}
              >
                {plan.popular && (
                  <motion.div
                    initial={{ opacity: 0, y: -10 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: 0.3, type: "spring" }}
                    className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-gradient-to-r from-primary to-accent px-4 py-1 text-xs font-bold text-primary-foreground"
                  >
                    Most Popular
                  </motion.div>
                )}
                <h3 className="font-display text-lg font-semibold">{plan.name}</h3>
                <div className="mt-3 flex items-baseline gap-1">
                  <motion.span
                    initial={{ opacity: 0, scale: 0.5 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    viewport={{ once: true }}
                    transition={{ delay: i * 0.1 + 0.2, type: "spring", stiffness: 200 }}
                    className="font-display text-4xl font-bold"
                  >
                    {plan.price}
                  </motion.span>
                  <span className="text-sm text-muted-foreground">{plan.period}</span>
                </div>
                <p className="mt-2 text-sm text-muted-foreground">{plan.desc}</p>
                <ul className="mt-6 space-y-3">
                  {plan.features.map((f, fi) => (
                    <motion.li
                      key={f}
                      initial={{ opacity: 0, x: -10 }}
                      whileInView={{ opacity: 1, x: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: fi * 0.05 + i * 0.1 + 0.3 }}
                      className="flex items-start gap-2 text-sm"
                    >
                      <Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                      <span className="text-foreground/80">{f}</span>
                    </motion.li>
                  ))}
                </ul>
                <Button
                  variant={plan.popular ? "gradient" : "outline"}
                  className="mt-6 w-full"
                  onClick={handleCTA}
                >
                  {plan.cta}
                </Button>
              </motion.div>
            ))}
          </div>
        </div>
      </ParallaxSection>

      {/* ── Final CTA ── */}
      <section className="relative border-t border-border py-20 sm:py-28 overflow-hidden">
        {/* Floating glow */}
        <motion.div
          animate={{ scale: [1, 1.2, 1], opacity: [0.3, 0.5, 0.3] }}
          transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
          className="pointer-events-none absolute left-1/2 top-1/2 h-[400px] w-[600px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary/8 blur-[100px]"
        />
        <div className="container relative text-center">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
          >
            <motion.h2 variants={fadeUp} custom={0} className="font-display text-3xl font-bold sm:text-4xl">
              Ready to Go <span className="gradient-text">Viral</span>?
            </motion.h2>
            <motion.p variants={fadeUp} custom={1} className="mx-auto mt-4 max-w-lg text-muted-foreground">
              Join thousands of creators using AI to generate scroll-stopping content every day.
            </motion.p>
            <motion.div
              variants={fadeUp}
              custom={2}
              className="mt-8"
            >
              <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.97 }}>
                <Button variant="gradient" size="lg" onClick={handleCTA} className="animate-pulse-glow px-8 text-base">
                  <Sparkles className="mr-2 h-5 w-5" />
                  Start Generating — It's Free
                </Button>
              </motion.div>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className="border-t border-border py-10">
        <div className="container flex flex-col items-center justify-between gap-4 sm:flex-row">
          <div className="flex items-center gap-2">
            <Zap className="h-5 w-5 text-primary" />
            <span className="font-display text-sm font-bold">
              <span className="gradient-text">Viral Reel</span> Generator
            </span>
          </div>
          <p className="text-sm text-muted-foreground">
            © {new Date().getFullYear()} Viral Reel Generator. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
